### ISSUE TITLE
Quartz lantern recipe not available

### ISSUE THREAD

**Issue by quartzlantern** [Omni-MC/LanternsPlus#3]
Hi,
Love the mod, but the quartz lantern recipe seem to be unavailable (recipe doesn't show up in in-game recipe book or JEI - the item shows up in JEI, but not the recipe). All the other lantern recipes show up both in the recipe book and in JEI. I can use the quartz lantern in creative mode, but I would love to be able to make it in my survival world if possible. I'm using version 1.16.5.

**Comment by OmniFS** [comment]
I had forgotten to add a recipe json. Fixed
